name: "Voltronic"
description: "Monitor and control Voltronic based inverters from Home Assistant."
version: "1.0.0"
slug: "voltronic"
init: false
udev: true
devices:
  - /dev/ttyS0
  - /dev/ttyUSB0
  - /dev/hidraw0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  mqtt_broker_host: "core-mosquitto"
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_password"
  device_type: usb-serial
  device_name: "inverter"
  device_manuf: "manufacturer"
  device_model: "model"
  device_serial: "0000"
  device_fw: "0.00"

schema:
  mqtt_broker_host: str
  mqtt_username: str
  mqtt_password: str
  device_type: list(serial|usb-serial|usb)
  device_name: str
  device_manuf: str
  device_model: str
  device_serial: str
  device_fw: str
